apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-udemy
  name: nginx-udemy
spec:
  containers:
  - image: nginx
    name: nginx-udemy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
